### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by matteos1** [steps39/Domoticz_Smappee#2] opened 2018-04-06 19:22 UTC
when a i start the script this is the error

**Comment by matteos1** [comment] 2018-04-06 19:22
"errorMessage":"The server encountered an unexpected condition which prevented it from fulfilling the request"

**Comment by steps39** [comment] 2018-04-08 18:14
matteos1, sorry to hear you are having problems, but I need a bit more detail to be able to understand what the problem is - smappee.sh calls smappee.lua - which creates log file by default in /var/tmp - smappee.log and smappe.log.errors if something goes wrong.  Have these files been created?  Have you gone through all the steps in the readme.md and any corrections made on the domoticz wiki?

I don't recognise the format of the error message or the error, however as it refers to a server I would first look at all the Domoticz parameters and all the Smappee server parameters and check they are ok.  Googling looks like these errors are normally due to login issues.

If nothing fixes it, then please upload smappee.log and smappee.log.errors - removing identifying details - i.e usernames / passwords / secrets from the file.

**Comment by matteos1** [comment] 2018-04-08 18:21
Ok all the system worked well but after update of raspberry pi  : libssl-dev libssl-doc libssl1.0.2 libssl1.1 openssl
I have problem to send on off to plug.
System is Linux DietPi 4.4.36-v7+ #933 SMP Fri Dec 2 22:03:01 GMT 2016 armv7l GNU/Linux
8.0

And
ii  libcurl4-openssl-dev:armhf                                       7.38.0-4+deb8u10                                          armhf        development files and documentation for libcurl (OpenSSL flavour)
ii  libflac8:armhf                                                   1.3.0-3                                                   armhf        Free Lossless Audio Codec - runtime C library
ii  libgnutls-openssl27:armhf                                        3.3.8-6+deb8u7                                            armhf        GNU TLS library - OpenSSL wrapper
ii  libssl-dev:armhf                                                 1.0.1t-1+deb8u8                                           armhf        Secure Sockets Layer toolkit - development files
ii  libssl-doc                                                       1.0.1t-1+deb8u8                                           all          Secure Sockets Layer toolkit - development documentation
ii  libssl1.0.0:armhf                                                1.0.1t-1+deb8u8                                           armhf        Secure Sockets Layer toolkit - shared libraries
ii  libwavpack1:armhf                                                4.70.0-1                                                  armhf        audio codec (lossy and lossless) - library
ii  openssl                                                          1.0.1t-1+deb8u8                                           armhf        Secure Sockets Layer toolkit - cryptographic utility
ii  python-openssl                                                   0.13.1-2                                                  armhf        Python 2 wrapper around the OpenSSL library
ii  ssl-cert                                                         1.0.35                                                    all          simple debconf wrapper for OpenSSL

**Comment by matteos1** [comment] 2018-04-08 18:23
message error
{"errorMessage":"The server encountered an unexpected condition which prevented it from fulfilling the request"}

**Comment by steps39** [comment] 2018-04-08 20:37
If you have a search through the Domoticz forums, there is a lot of mention of issues with libssl1.1, are you running into that problem?  If so the answer is to downgrade libssl.
Which version of Raspbian are you running - Wheezy, Jeezy, Stretch?  I haven't tried Stretch.
I think there was an official post on the forum, but this recent post refers to the issue and offers a fix - http://www.domoticz.com/forum/viewtopic.php?f=47&t=22847&p=177396&hilit=libssl#p177396

**Comment by matteos1** [comment] 2018-04-08 20:40
Jeezy

**Comment by matteos1** [comment] 2018-04-08 20:41
How can I downgrade libssl1.1?

**Comment by steps39** [comment] 2018-04-08 21:33
Have a read of the instructions in the forum post I pointed you to, I have not seen this issue myself and so don't know what solution will work.
It also looks like you are not running standard Raspbian, but the DietPi version, which I guess could also cause issues.

**Comment by matteos1** [comment] 2018-04-08 21:50
yes dietpi version

**Comment by matteos1** [comment] 2018-04-09 15:30
do you have this version of software of smappee ??
cause till 29/03/2018 not work

Nr of features received from acquisition engine | 66890
-- | --
Last software update | 29/03/2018 12:15:39
Application software version and build nr | 1.0.0S buildNr #1185

**Comment by steps39** [comment] 2018-04-09 19:07
I appear to have a more recent version, but build number is lower:

Monitor application |  
-- | --
Nr of signatures received from acquisition engine | 15312
Last software update | 08/04/2018 17:07:59
Application software version and build nr | 1.0.0S buildNr #1079
Acquisition Software version | 3.22
EMeter working config | single phase + single solar
EMeter type | SmappeeT
OS build nr | 8
Gas/Water sensors | N/A
Timezone | Greenwich Mean Time
Time&Date | 09/04/2018 20:02:55

You updated your system, so I still think it is the libssl issue, have you followed the instructions in the post to downgrade your libssl:
http://ftp.nl.debian.org/debian/pool/main/o/openssl/libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb
sudo dpkg -i libssl1.0.0_1.0.2l-1~bpo8+1_armhf.deb
I don't know if this will work on DietPi, so possibly worthwhile have a backup in case it causes other issues.

**Comment by matteos1** [comment] 2018-04-09 19:10
is not a problem of libssl cause also on another raspberry give the same error
so i think that is smappee update

> this

 is error in var/tmp

lua: /usr/local/share/lua/5.2/JSON.lua:383: html passed to JSON:decode(): <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.2/JSON.lua:383: in function 'onDecodeOfHTMLError'
	/usr/local/share/lua/5.2/JSON.lua:655: in function 'decode'
	/root/domoticz_smappee/smappee.lua:45: in function 'variable_list'
	/root/domoticz_smappee/smappee.lua:51: in function 'idx_from_variable_name'
	/root/domoticz_smappee/smappee.lua:108: in function 'retrieve_Domoticz_variable'
	/root/domoticz_smappee/smappee.lua:251: in main chunk
	[C]: in ?

>

**Comment by steps39** [comment] 2018-04-10 08:46
The error you are seeing here is Domoticz refusing connection and nothing to do with the Smappee server.

Thinking about this, the software on your local Smappee box should have no effect, as the program talks to the Smappee server to get the data - https://app1pub.smappee.net.

So if you have a look at the top of the /var/tmp/smappee.log - then you will see the username / password for Domoticz, have you changed these recently? 

2018-04-01 17:35:02 - -------------------------------------------
2018-04-01 17:35:02 - Starting Smappee to Domoticz Energy Handler
2018-04-01 17:35:02 - -------------------------------------------
2018-04-01 17:35:02 - SmappeeClientSecret: 123456989
2018-04-01 17:35:02 - SmappeeClientID: ClientName
2018-04-01 17:35:02 - SmappeeUsername: username
2018-04-01 17:35:02 - SmappeePassword: password
2018-04-01 17:35:02 - DomoticzUsername not found check /etc/profile.d/DomoticzData.sh
2018-04-01 17:35:02 - DomoticzPassword not found check /etc/profile.d/DomoticzData.sh
2018-04-01 17:35:02 - DomoticzIP: 127.0.0.1
2018-04-01 17:35:02 - DomoticzPort: 8080
2018-04-01 17:35:02 - SmappeeHousehold: Smappee Household
.......
Are the IP / username / password for Domoticz correct in the log?  If not correct in /etc/profile.d/DomoticzData.sh

**Comment by matteos1** [comment] 2018-04-10 08:59
i've checked now..
all paramether are ok
coud be that last version of firmware have some problem with api to control plug?

Nr of features received from acquisition engine | 67264
-- | --
Last software update | 29/03/2018 12:15:39
Application software version and build nr | 1.0.0S buildNr #1185
Acquisition Software version | 4.29
EMeter working config | single phase
EMeter type | SmappeeT


OS build nr | 8
-- | --
Gas/Water sensors | 3004001022
Gas/Water sensor RF packets received | 65207
Timezone | Central European Time
Time&Date | 10/04/2018 11:01:35

**Comment by matteos1** [comment] 2018-04-10 09:22
responce of smappee support
Dear,

It is indeed possible that the scripts will not work anymore. This is because the new firmware #1185 has changed the communication protocol used by the Smappee and the plugs. 

The older firmware used websockets as communication protocol. The protocol was highly unstable though at weak network connectivity. Therefor we have changed to an overall more stable communcation protocol: MQTT. 

You will have to change your scripts so that it will be compatible with this new MQTT protocol. 

I will now change the status of this ticket to "solved".

If you need further assistance, please do not hesitate to reply to this mail within 4 days. Off course you can always create a new ticket as well.

With best regards,

**Comment by steps39** [comment] 2018-04-10 11:10
This program is talking to 2 server - your own Domoticz server and the Smappee company server, it does not talk to the Smappee box in your house, so change of protocol on the box does not affect the program.

The error you are seeing is an issue with accessing your local Domoticz server, not the Smappee company server.

I am having no problems currently with getting data back from the Smappee company server, neither is  Egregius based on his post on the Domoticz forum using php with same Smappee and Domoticz interaction methods as I am using:
DateTime | Energy Usage | Power Usage
2018-04-10 11:45:00 |   | 828
2018-04-10 11:50:00 |   | 1718.4
2018-04-10 11:55:00 |   | 2710.8
2018-04-10 12:00:00 |   | 862.8

All the evidence points to something have changed in Domoticz either your settings or a recent Domoticz update - I am using Domoticz 3.8807 the latest beta 3.9208, however I am using such simple interaction with Domoticz that if this was the cause the forum would be full of other people having errors, which I haven't seen.

The only other thing to suggest is you let restart this program, let it fail and then send me smappee.log, smappee.log.error, DomoticzData.sh to see if I can spot anything amiss.

**Comment by matteos1** [comment] 2018-04-10 11:28
The script was installed on 2 different raspberry and on both there is no communication with the switches.

a diet is installed on a raspberry and raspbian is installed on the other.
I still manage to read the values of smappee, watt etc etc.
smappe, however, has confirmed that there was a firmware update and to me from 29/03/2018 (update date) checks on domoticz do not work.
I do not know if this change of the update has influenced the operation in domoticz

i send you the smappee.log, smappee.log.error, DomoticzData.sh
[smappee.log](https://github.com/steps39/Domoticz_Smappee/files/1894345/smappee.log)

[smappee.log.errors.txt](https://github.com/steps39/Domoticz_Smappee/files/1894347/smappee.log.errors.txt)
[DomoticzData.sh.txt](https://github.com/steps39/Domoticz_Smappee/files/1894354/DomoticzData.sh.txt)

**Comment by steps39** [comment] 2018-04-10 13:23
Ok, I read in the Domoticz username and password, but they are not used anywhere in the code, so if you remove the need for authentication from your Domoticz, then the program should work or at least get past the current error.

So, I can only assume that if it was working for you before then, you recently turned on the need for authentication on your Domoticz server.

If you want to keep authentication, then you need to change the code, line 156 in smappe.lua: 
server_url = "http://"..DomoticzIP..":"..DomoticzPort
to:
server_url = "http://"..DomoticzUser..":"..DomoticzPassword.."@"..DomoticzIP..":"..DomoticzPort
This should then work with authentication.

I will add this modification into the main code.

**Comment by matteos1** [comment] 2018-04-10 13:27
ok wait for your changes
thank you

**Comment by steps39** [comment] 2018-04-10 14:20
Changes for authentication added to master branch, please test and check it work for you.

**Comment by matteos1** [comment] 2018-04-10 23:06
error in log and i cannot control plug
[smappee.log.errors.txt](https://github.com/steps39/Domoticz_Smappee/files/1896720/smappee.log.errors.txt)

**Comment by steps39** [comment] 2018-04-11 05:58
The error is a spelling mistake, I have committed a corrected version, please test.

I am not sure what you mean by "cannot control plug", Domoticz_smappee only receives information from smappee and does not interact with any smappee rf electrical plugs.

**Comment by matteos1** [comment] 2018-04-11 07:41
ok and from [](https://www.domoticz.com/wiki/Smappee)

https://www.domoticz.com/wiki/Smappee

Checking Functioning
If smappee.lua is running properly, then smappee.log will have been created and data will be uploaded to Domoticz.

Wait 5 minutes and data should have appeared in Domoticz, on at least one of the virtual energy meters.

Check smappee.log which will have been created if smappee.lua has excuted.

If there is a problem with the program, then smappee.log.errors will have been created.

Controlling Smappee, including confort plugs, through the internal API
Smappee also allows you to control plugs (actuators) using the 433 Mhz frequency. The brand sells plugs DIO produced by Chacon, but Smappee works also with most other brands which sell plugs and other switches compatible with the Home Easy protocol. Through the Smappee monitor (http://<your smappee ip>/smappee.html, default logon "admin") it is possible to control the plugs and access some other useful information. This allows us also to bypass the external API and control the plugs directly, which regarding the plug control is a clear advantage in terms of speed and reliability. One way to do this is through simple bash scripts.

Smappee internal API has the following commands:

http://<your smappee ip>/gateway/apipublic/logon
http://<your smappee ip>/gateway/apipublic/statisticsPublicReport
http://<your smappee ip>/gateway/apipublic/reportInstantaneousValues
http://<your smappee ip>/gateway/apipublic/restartEMeter
http://<your smappee ip>/gateway/apipublic/commandControlPublic
To login on the Smappee local API with curl, just use:

curl -H "Content-Type: application/json" -X POST -d "<your_logon>" http://<your smappee ip>/gateway/apipublic/logon
Through this API you can easily create a script to turn on an off the plugs. For example to turn on the plug with the ID 8:

#!/bin/bash
curl -H "Content-Type: application/json" -X POST -d "<your_logon>" http://<your smappee ip>/gateway/apipublic/logon
curl -H "Content-Type: application/json" -X POST -d "control,controlId=1|8" http://<your smappee ip>/gateway/apipublic/commandControlPublic
To turn it off, your script just needs to change the first number after the controlID to 0:

#!/bin/bash
curl -H "Content-Type: application/json" -X POST -d "<your_logon>" http://<your smappee ip>/gateway/apipublic/logon
curl -H "Content-Type: application/json" -X POST -d "control,controlId=0|8" http://<your smappee ip>/gateway/apipublic/commandControlPublic
To get a list of your plug IDs for the previous scripts just use:

curl -H "Content-Type: application/json" -X POST -d "load" http://<your smappee ip>/gateway/apipublic/commandControlPublic
Don't forget to make the files executable, for example:

sudo chmod +x plug_sofa_off.sh
**not work the comunication between smappee and  rf electrical plugs**

**Comment by matteos1** [comment] 2018-04-11 08:19
smappe support
Dear,

Our development service has not yet uploaded the documentation which explains how to use the new MQTT protocol. Once this is uploaded, it will be uploaded to the same confluence page as the dev API. For now however this is not yet available. 
I have forwarded the scripts to my development team. They will look at the scripts and inform me how they need to be changed to use MQTT however this is not of their usual tasks. They have informed me it could possibly take some time. 

Once i have more information, i will definitely let you know.

**Comment by steps39** [comment] 2018-04-11 10:14
Ok, so I assume from your last message that Domoticz_smappee is now working on your system as authentication is now included.

The issue that the Smappee company has changed the protocol to communicate with your local smappee box is not related to this program, so I will close this issue.

The Domiticz page you refer to is a wiki, so worthwhile adding a comment on the page that the software update has now disabled the protocol referred to for controlling plugs directly.  You might start a discussion on the Domoticz forum, but strictly not directly Domoticz related, is there a Smappee discussion forum?  However, reasonable to ask how others are working with Domoticz and Smappee on the Domoticz forum.  If Smappee reply with instructions on how to use MQTT then they may be helpful to put on the Domoticz wiki.  Of course Domoticz can handle MQTT, but I haven't used it, so that may be a route to follow up as well on, once Smappee have written the documentation.

**Closed as completed** 2018-04-12 18:49 UTC
